version: 0.2

phases:
  install:
    commands:
      - echo "No hay dependencias que instalar para un sitio estático."

  build:
    commands:
      - echo "Copiando archivos a la carpeta de distribución..."
      - mkdir -p dist
      - find . -type f ! -name ".*" -exec cp --parents {} dist/ \;

  post_build:
    commands:
      - echo "No hay bucket de S3 configurado. Omitting deployment step."

artifacts:
  files:
    - '**/*'
  discard-paths: yes
